"""Evolved strategy: Persona Capability Matcher

Auto-generated by agos evolution engine.
Source paper: 2602.15028v1
Target module: intent.personas
Generated: 2026-02-17T21:29:31.984844
Defines: Persona, match_persona
Code hash: 4302003c9b1f33f2

Sandbox output: Best match for {'audit', 'analyze', 'read'}: reviewer (score=1.0)
PASS: Persona capability matcher validated

"""

from __future__ import annotations

import logging
from typing import Any

from agos.evolution.integrator import IntegrationStrategy, EvolutionProposal

_logger = logging.getLogger(__name__)

# ── Evolved pattern code ──────────────────────────────────────────
# This code passed sandbox validation and EXECUTES when apply() is called.

PATTERN_CODE = "class Persona:\n    def __init__(self, name, capabilities, budget, max_turns):\n        self.name = name\n        self.capabilities = set(capabilities)\n        self.budget = budget\n        self.max_turns = max_turns\n\ndef match_persona(task_needs, personas):\n    scored = []\n    for p in personas:\n        overlap = len(task_needs & p.capabilities)\n        coverage = overlap / max(len(task_needs), 1)\n        efficiency = overlap / max(len(p.capabilities), 1)\n        score = 0.6 * coverage + 0.4 * efficiency\n        scored.append((p, round(score, 3)))\n    scored.sort(key=lambda x: -x[1])\n    return scored\n\npersonas = [\n    Persona('researcher', {'search', 'read', 'analyze', 'http'}, 200000, 30),\n    Persona('coder', {'write', 'shell', 'python', 'test'}, 200000, 40),\n    Persona('reviewer', {'read', 'analyze', 'audit'}, 100000, 20),\n    Persona('orchestrator', {'search', 'read', 'write', 'shell', 'http', 'python'}, 300000, 50),\n]\nneed = {'read', 'analyze', 'audit'}\nranked = match_persona(need, personas)\nassert ranked[0][0].name == 'reviewer'\nprint(f'Best match for {need}: {ranked[0][0].name} (score={ranked[0][1]})')\nprint('PASS: Persona capability matcher validated')\n"

PATTERN_HASH = "4302003c9b1f33f2"


def _execute_pattern() -> dict[str, Any]:
    """Execute the pattern code and return all defined names."""
    namespace = {"__builtins__": __builtins__}
    exec(compile(PATTERN_CODE, "<evolved:persona_capability_matcher>", "exec"), namespace)
    return {k: v for k, v in namespace.items()
            if not k.startswith("_") and k != "__builtins__"}


# ── Strategy wrapper ──────────────────────────────────────────────


class PersonaCapabilityMatcherStrategy(IntegrationStrategy):
    """Evolved strategy that EXECUTES: Persona Capability Matcher"""

    name = "persona_capability_matcher"
    target_module = "intent.personas"

    def __init__(self, components: dict[str, Any] | None = None, **kwargs: Any) -> None:
        self._components = components or {}
        self._applied = False
        self._exports: dict[str, Any] = {}

    def validate(self, proposal: EvolutionProposal) -> tuple[bool, str]:
        return True, ""

    async def snapshot(self) -> dict[str, Any]:
        return {"applied": self._applied}

    async def apply(self, proposal: EvolutionProposal) -> list[str]:
        changes: list[str] = []

        # Execute the pattern code for real
        try:
            self._exports = _execute_pattern()
        except Exception as e:
            _logger.warning("Pattern execution failed for persona_capability_matcher: %s", e)
            return [f"Pattern execution failed: {e}"]

        exported = [k for k in self._exports
                    if callable(self._exports[k]) or isinstance(self._exports[k], type)]
        if exported:
            changes.append(f"Executed pattern, defined: {', '.join(exported[:10])}")
        else:
            changes.append("Executed pattern (no callable exports)")

        # Hook into live system components
        loom = self._components.get("loom")
        event_bus = self._components.get("event_bus")
        audit_trail = self._components.get("audit_trail")
        target = "intent.personas"

        # Wire exported functions/classes into the target component
        if target.startswith("knowledge") and loom is not None:
            semantic = getattr(loom, "semantic", None)
            for fn_name, obj in self._exports.items():
                if callable(obj) and not isinstance(obj, type):
                    if semantic is not None and not hasattr(semantic, f"_evolved_{fn_name}"):
                        setattr(semantic, f"_evolved_{fn_name}", obj)
                        changes.append(f"Hooked {fn_name}() into semantic weave")
                    elif not hasattr(loom, f"_evolved_{fn_name}"):
                        setattr(loom, f"_evolved_{fn_name}", obj)
                        changes.append(f"Hooked {fn_name}() into knowledge manager")
                elif isinstance(obj, type):
                    if semantic is not None and not hasattr(semantic, f"_evolved_{fn_name}"):
                        setattr(semantic, f"_evolved_{fn_name}", obj)
                        changes.append(f"Registered {fn_name} class in semantic weave")

        elif target.startswith("intent") and audit_trail is not None:
            for fn_name, obj in self._exports.items():
                if callable(obj) and not isinstance(obj, type):
                    if not hasattr(audit_trail, f"_evolved_{fn_name}"):
                        setattr(audit_trail, f"_evolved_{fn_name}", obj)
                        changes.append(f"Hooked {fn_name}() into intent system")

        elif target == "policy" and audit_trail is not None:
            for fn_name, obj in self._exports.items():
                if callable(obj) or isinstance(obj, type):
                    if not hasattr(audit_trail, f"_evolved_{fn_name}"):
                        setattr(audit_trail, f"_evolved_{fn_name}", obj)
                        changes.append(f"Hooked {fn_name} into policy system")

        elif target.startswith("orchestration") and event_bus is not None:
            for fn_name, obj in self._exports.items():
                if callable(obj) or isinstance(obj, type):
                    if not hasattr(event_bus, f"_evolved_{fn_name}"):
                        setattr(event_bus, f"_evolved_{fn_name}", obj)
                        changes.append(f"Hooked {fn_name} into orchestration")

        if not changes:
            changes.append("Pattern executed but no hookable exports found")

        self._applied = True
        changes.append("Source: 2602.15028v1")
        return changes

    async def rollback(self, snapshot_data: dict[str, Any]) -> None:
        loom = self._components.get("loom")
        event_bus = self._components.get("event_bus")
        audit_trail = self._components.get("audit_trail")
        for fn_name in self._exports:
            for comp in [loom, getattr(loom, "semantic", None) if loom else None,
                         event_bus, audit_trail]:
                if comp is not None:
                    attr = f"_evolved_{fn_name}"
                    if hasattr(comp, attr):
                        try:
                            delattr(comp, attr)
                        except Exception:
                            pass
        self._applied = snapshot_data.get("applied", False)

    async def health_check(self) -> bool:
        try:
            _execute_pattern()
            return True
        except Exception:
            return False
