"""Community contribution — share evolution learnings via GitHub PR.

Uses the GitHub API to fork the main repo (if needed), create a branch,
commit a contribution JSON file, and open a pull request.
"""

from __future__ import annotations

import json
import base64
from datetime import datetime

import httpx

from agos.config import settings

GITHUB_API = "https://api.github.com"


class ContributionError(Exception):
    """Failed to create a community contribution."""


async def share_learnings(
    contribution: dict,
    github_token: str,
    upstream_owner: str | None = None,
    upstream_repo: str | None = None,
) -> dict:
    """Create a GitHub PR with this instance's evolution learnings.

    Returns {"pr_url": "...", "branch": "..."}.
    Raises ContributionError on failure.
    """
    owner = upstream_owner or settings.github_owner
    repo = upstream_repo or settings.github_repo
    instance_id = contribution.get("instance_id", "unknown")[:12]
    timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    branch_name = f"contrib/{instance_id}/{timestamp}"
    file_path = f"community/contributions/{instance_id}.json"

    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json",
    }

    async with httpx.AsyncClient(
        timeout=30, headers=headers, follow_redirects=True
    ) as client:
        # Step 1: Get authenticated user
        fork_user = await _get_authenticated_user(client)

        # Step 2: Fork the repo (idempotent)
        await _ensure_fork(client, owner, repo)

        # Step 3: Get default branch SHA from fork
        default_sha = await _get_default_branch_sha(client, fork_user, repo)

        # Step 4: Create branch on fork
        await _create_branch(client, fork_user, repo, branch_name, default_sha)

        # Step 5: Commit contribution file
        content_b64 = base64.b64encode(
            json.dumps(contribution, indent=2).encode("utf-8")
        ).decode("ascii")
        await _commit_file(
            client, fork_user, repo, file_path, content_b64, branch_name,
            message=f"Add evolution learnings from instance {instance_id}",
        )

        # Step 6: Open PR against upstream
        n_strategies = len(contribution.get("strategies_applied", []))
        n_cycles = contribution.get("cycles_completed", 0)
        n_patterns = len(contribution.get("discovered_patterns", []))

        pr_title = (
            f"[Community] Evolution learnings: "
            f"{n_strategies} strategies, {n_cycles} cycles"
        )
        pr_body = (
            f"## Community Evolution Contribution\n\n"
            f"- **Instance:** `{instance_id}`\n"
            f"- **Cycles completed:** {n_cycles}\n"
            f"- **Strategies applied:** {n_strategies}\n"
            f"- **Patterns discovered:** {n_patterns}\n\n"
        )
        if contribution.get("strategies_applied"):
            pr_body += "### Strategies\n"
            for s in contribution["strategies_applied"]:
                pr_body += (
                    f"- **{s['name']}** (module: `{s['module']}`, "
                    f"applied {s.get('applied_count', 1)}x)\n"
                )
            pr_body += "\n"

        pr_body += "---\n*Auto-generated by AGenticOS evolution engine.*\n"

        pr_url = await _create_pr(
            client, owner, repo,
            head=f"{fork_user}:{branch_name}",
            base="main",
            title=pr_title,
            body=pr_body,
        )

    return {"pr_url": pr_url, "branch": branch_name}


# ── GitHub API helpers ───────────────────────────────────────────


async def _get_authenticated_user(client: httpx.AsyncClient) -> str:
    resp = await client.get(f"{GITHUB_API}/user")
    if resp.status_code != 200:
        raise ContributionError(
            f"Auth failed ({resp.status_code}): check your GitHub token"
        )
    return resp.json()["login"]


async def _ensure_fork(
    client: httpx.AsyncClient, owner: str, repo: str
) -> None:
    resp = await client.post(f"{GITHUB_API}/repos/{owner}/{repo}/forks")
    if resp.status_code not in (200, 202):
        raise ContributionError(f"Fork failed: {resp.status_code}")


async def _get_default_branch_sha(
    client: httpx.AsyncClient, owner: str, repo: str
) -> str:
    resp = await client.get(f"{GITHUB_API}/repos/{owner}/{repo}")
    if resp.status_code != 200:
        raise ContributionError(f"Repo not found: {resp.status_code}")
    default_branch = resp.json().get("default_branch", "main")
    ref = await client.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/ref/heads/{default_branch}"
    )
    if ref.status_code != 200:
        raise ContributionError(f"Branch ref failed: {ref.status_code}")
    return ref.json()["object"]["sha"]


async def _create_branch(
    client: httpx.AsyncClient, owner: str, repo: str,
    branch: str, sha: str,
) -> None:
    resp = await client.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/git/refs",
        json={"ref": f"refs/heads/{branch}", "sha": sha},
    )
    if resp.status_code not in (200, 201):
        raise ContributionError(f"Branch creation failed: {resp.status_code}")


async def _commit_file(
    client: httpx.AsyncClient, owner: str, repo: str,
    path: str, content_b64: str, branch: str, message: str,
) -> None:
    # Check if file exists (need SHA for update)
    existing_sha = None
    check = await client.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/contents/{path}",
        params={"ref": branch},
    )
    if check.status_code == 200:
        existing_sha = check.json().get("sha")

    payload: dict = {
        "message": message,
        "content": content_b64,
        "branch": branch,
    }
    if existing_sha:
        payload["sha"] = existing_sha

    resp = await client.put(
        f"{GITHUB_API}/repos/{owner}/{repo}/contents/{path}",
        json=payload,
    )
    if resp.status_code not in (200, 201):
        raise ContributionError(f"Commit failed: {resp.status_code}")


async def _create_pr(
    client: httpx.AsyncClient, owner: str, repo: str,
    head: str, base: str, title: str, body: str,
) -> str:
    resp = await client.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
        json={"title": title, "body": body, "head": head, "base": base},
    )
    if resp.status_code not in (200, 201):
        raise ContributionError(f"PR creation failed: {resp.status_code}")
    return resp.json().get("html_url", "")
